# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
